use serde::Deserialize;
use serde_derive::Serialize;
use strum::{Display, EnumDiscriminants, EnumIter, IntoEnumIterator};

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CurrencyExchange {
    pub result: String,
    pub rates: Rates,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub struct Rates {
    pub usd: f64,
    pub aed: f64,
    pub afn: f64,
    pub all: f64,
    pub amd: f64,
    pub ang: f64,
    pub aoa: f64,
    pub ars: f64,
    pub aud: f64,
    pub awg: f64,
    pub azn: f64,
    pub bam: f64,
    pub bbd: f64,
    pub bdt: f64,
    pub bgn: f64,
    pub bhd: f64,
    pub bif: f64,
    pub bmd: f64,
    pub bnd: f64,
    pub bob: f64,
    pub brl: f64,
    pub bsd: f64,
    pub btn: f64,
    pub bwp: f64,
    pub byn: f64,
    pub bzd: f64,
    pub cad: f64,
    pub cdf: f64,
    pub chf: f64,
    pub clp: f64,
    pub cny: f64,
    pub cop: f64,
    pub crc: f64,
    pub cup: f64,
    pub cve: f64,
    pub czk: f64,
    pub djf: f64,
    pub dkk: f64,
    pub dop: f64,
    pub dzd: f64,
    pub egp: f64,
    pub ern: f64,
    pub etb: f64,
    pub eur: f64,
    pub fjd: f64,
    pub fkp: f64,
    pub fok: f64,
    pub gbp: f64,
    pub gel: f64,
    pub ggp: f64,
    pub ghs: f64,
    pub gip: f64,
    pub gmd: f64,
    pub gnf: f64,
    pub gtq: f64,
    pub gyd: f64,
    pub hkd: f64,
    pub hnl: f64,
    pub hrk: f64,
    pub htg: f64,
    pub huf: f64,
    pub idr: f64,
    pub ils: f64,
    pub imp: f64,
    pub inr: f64,
    pub iqd: f64,
    pub irr: f64,
    pub isk: f64,
    pub jep: f64,
    pub jmd: f64,
    pub jod: f64,
    pub jpy: f64,
    pub kes: f64,
    pub kgs: f64,
    pub khr: f64,
    pub kid: f64,
    pub kmf: f64,
    pub krw: f64,
    pub kwd: f64,
    pub kyd: f64,
    pub kzt: f64,
    pub lak: f64,
    pub lbp: f64,
    pub lkr: f64,
    pub lrd: f64,
    pub lsl: f64,
    pub lyd: f64,
    pub mad: f64,
    pub mdl: f64,
    pub mga: f64,
    pub mkd: f64,
    pub mmk: f64,
    pub mnt: f64,
    pub mop: f64,
    pub mru: f64,
    pub mur: f64,
    pub mvr: f64,
    pub mwk: f64,
    pub mxn: f64,
    pub myr: f64,
    pub mzn: f64,
    pub nad: f64,
    pub ngn: f64,
    pub nio: f64,
    pub nok: f64,
    pub npr: f64,
    pub nzd: f64,
    pub omr: f64,
    pub pab: f64,
    pub pen: f64,
    pub pgk: f64,
    pub php: f64,
    pub pkr: f64,
    pub pln: f64,
    pub pyg: f64,
    pub qar: f64,
    pub ron: f64,
    pub rsd: f64,
    pub rub: f64,
    pub rwf: f64,
    pub sar: f64,
    pub sbd: f64,
    pub scr: f64,
    pub sdg: f64,
    pub sek: f64,
    pub sgd: f64,
    pub shp: f64,
    pub sle: f64,
    pub sll: f64,
    pub sos: f64,
    pub srd: f64,
    pub ssp: f64,
    pub stn: f64,
    pub syp: f64,
    pub szl: f64,
    pub thb: f64,
    pub tjs: f64,
    pub tmt: f64,
    pub tnd: f64,
    pub top: f64,
    #[serde(rename = "TRY")]
    pub try_field: f64,
    pub ttd: f64,
    pub tvd: f64,
    pub twd: f64,
    pub tzs: f64,
    pub uah: f64,
    pub ugx: f64,
    pub uyu: f64,
    pub uzs: f64,
    pub ves: f64,
    pub vnd: f64,
    pub vuv: f64,
    pub wst: f64,
    pub xaf: f64,
    pub xcd: f64,
    pub xdr: f64,
    pub xof: f64,
    pub xpf: f64,
    pub yer: f64,
    pub zar: f64,
    pub zmw: f64,
    pub zwl: f64,
}

#[derive(Debug, EnumIter, Display, EnumDiscriminants)]
pub enum Currencies {
    USD,
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BZD,
    CAD,
    CDF,
    CHF,
    CLP,
    CNY,
    COP,
    CRC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    FOK,
    GBP,
    GEL,
    GGP,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    IMP,
    INR,
    IQD,
    IRR,
    ISK,
    JEP,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KID,
    KMF,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLE,
    SLL,
    SOS,
    SRD,
    SSP,
    STN,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TTD,
    TVD,
    TWD,
    TZS,
    UAH,
    UGX,
    UYU,
    UZS,
    VES,
    VND,
    VUV,
    WST,
    XAF,
    XCD,
    XDR,
    XOF,
    XPF,
    YER,
    ZAR,
    ZMW,
    ZWL,
}
